name: synpuf_pipeline
channels:
  - defaults
dependencies:
  - dash=2.14.2
  - dask=2025.2.0
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - numpy=2.0.1
  - pandas=2.2.3
  - pip=25.1
  - plotly=6.0.1
  - pytest=8.4.1
  - python=3.10.18
  - pyyaml=6.0.2
  - seaborn=0.13.2
  - yaml=0.2.5
