name: synpuf_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - numpy=2.0.1
  - pandas=2.2.3
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - seaborn=0.13.2  
  - pytest=8.3.4
  - pyyaml=6.0.2
  - pip=25.1